//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContosoSite.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Sostav_of_project
    {
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd'/'MM'/'yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime Data_including { get; set; }
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd'/'MM'/'yyyy}", ApplyFormatInEditMode = true)]
        public Nullable<System.DateTime> Date_outsiding { get; set; }
        public System.Guid ID_Musican { get; set; }
        public System.Guid ID_Project { get; set; }
        public int Code_role { get; set; }
        public virtual Musicians Musicians { get; set; }
        public virtual Projects Projects { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
